### PR TITLE
Add promotion video to homepage

### LINKED ISSUE #12: Add NL-RSE video to the home page
I made three sketches. Which one do you like most? any other alternative?

### PR DESCRIPTION
**Pull request by ctwhome**
Fixes #12

See preview here: https://deploy-preview-28--nl-rse.netlify.app/

### CODE REVIEW

**Comment by c-martinez** [comment]
I'm not sure, it looks a bit crowded. What do others think?

**Comment by ctwhome** [comment]
I actually like the composition, maybe making the texts of the button and the intro might help?

**Comment by c-martinez** [comment]
As discussed, maybe blurring the background a bit? But let's ask @liekelotte for her opinion.

**Comment by ctwhome** [comment]
Which versions do you like? @c-martinez @liekelotte 

Original: 



these could be an alternative:

**Comment by c-martinez** [comment]
I like Option 2 the best, followed by Option 3. But let's say @liekelotte has the deciding vote :-)

**Comment by liekelotte** [comment]
Option 3 looks more symmetrical to me?

**Comment by ctwhome** [comment]
Op 3 then, top

**Pull request merged**
